"""add-user-without-username

Revision ID: 4c7052092665
Revises: e745463a6f06
Create Date: 2023-05-01 13:30:09.655050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from models.user import User

# revision identifiers, used by Alembic.
revision = '4c7052092665'
down_revision = 'e745463a6f06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with Session(op.get_bind()) as session:
        users = [
            User(
                first_name="Tomas",
                last_name="Svojanovsky",
                email="a@b.com",
            )
        ]
        session.add_all(users)
        session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
